### DISCUSSION TITLE
Chocolatey / GitLab runner compatibility?

### DISCUSSION THREAD

**Discussion by cjhines** [microsoft/react-native-windows#10260] [Q&A] [answered]
I'm trying to build a rn-windows app on a [GitLab Windows Shared Runner](https://about.gitlab.com/blog/2020/01/21/windows-shared-runner-beta/). These should have Visual Studio 2019 Build Tools included [as outlined here](https://gitlab.com/gitlab-org/ci-cd/shared-runners/images/gcp/windows-containers/blob/main/cookbooks/preinstalled-software/README.md).

However whenever I run `npx react-native run-windows --arch x64 --release --logging` it never finds this:

```
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
- No public VS release found
⚠ No public VS release found
- Trying pre-release VS
ℹ Trying pre-release VS
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
- Could not find MSBuild with VCTools for Visual Studio 16.7 or later. Make sure all required components have been installed
✖ Could not find MSBuild with VCTools for Visual Studio 16.7 or later. Make sure all required components have been installed
```

I even tried installing the `visualstudio2019community` package with chocolatey first, but I get the same result. Any ideas?

Here's my GitLab configuration file:

```
.shared_windows_runners:
  tags:
    - shared-windows
    - windows
    - windows-1809

stages:
  - build

build_windows:
  extends:
    - .shared_windows_runners
    - .deploy
  stage: build
  before_script:
    - start powershell
    - cd application
  script:
    - choco install nodejs --version 14.20.0 -y --no-progress
    - choco install visualstudio2019community -y --no-progress
    - npm ci
    - npx react-native run-windows --arch x64 --release --logging
```
