### DISCUSSION TITLE
Unable to build newly set up app in monorepo

### DISCUSSION THREAD

**Discussion by shirakaba** [microsoft/react-native-windows#13481] [Q&A] [answered]
I'm making an app in a `pnpm` monorepo on a Windows VM, and I'm unfamiliar with Windows dev, so bear with me.

I've completed the [environment setup](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies) steps, running the following as an administrator in Powershell:

```sh
PS C:\Windows\system32> Set-ExecutionPolicy Unrestricted -Scope Process -Force;
PS C:\Windows\system32> C:\Users\jamie\git\banana_native\node_modules\react-native-windows\scripts\rnw-dependencies.ps1
```

<details>
<summary>See react-native info</summary>

```yaml
System:
  OS: Windows 11 10.0.22631
  CPU: (4) x64 Apple Silicon
  Memory: 1002.04 MB / 7.99 GB
Binaries:
  Node:
    version: 20.15.0
    path: ~\AppData\Local\Volta\tools\image\node\20.15.0\node.EXE
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: ~\AppData\Local\Volta\tools\image\node\20.15.0\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.35027.167 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

</details>

However, when I try to run `react-native run-windows`, it seems it can't find a bunch of dependencies belonging to the `react-native-windows` package, because it's looking for `react-native-windows` in the workspace directory when it should be looking inside the monorepo root.

```
# It's searching in the node_modules inside my workspace:
<monorepo root>\apps\<workspace>\node_modules\react-native-windows

# However, the dependency is actually to be found higher up, inside the monorepo root's node_modules:
`<monorepo root>\node_modules\react-native-windows`:

# Again, with absolute paths:

# It's searching for:
C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj

# The dependency actually lives here:
C:\Users\jamie\git\banana_native\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj
```

<details>
<summary>See build logs for react-native run-windows</summary>

```
pnpm windows

> @shirakaba/banana-native@1.0.0 windows C:\Users\jamie\git\banana_native\apps\banana
> react-native run-windows

 MSBuild version 17.10.4+10fbfbf2e for .NET Framework
Build started 7/22/2024 5:46:08 PM.

Project "C:\Users\jamie\git\banana_native\apps\banana\windows
\banana.sln" on node 1 (Restore target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
C:\Program Files\Microsoft Visual Studio\2022\Community\Com
mon7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Folly\Folly.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\fmt\fmt.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Common\Common.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
Project "C:\Users\jamie\git\banana_native\apps\banana\windows
\banana.sln" (1) is building "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj" (3) on node 1 (_IsProjectRestoreSupported target(s)).
C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj'.
Done Building Project "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj" (_IsProjectRestoreSupported target(s)) -- FAILED.

Done Building Project "C:\Users\jamie\git\banana_native\apps
\banana\windows\banana.sln" (Restore target(s)) -- FAILED.


Build FAILED.

"C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln" (Restore target) (1) ->
(_FilterRestoreGraphProjectInputItems target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Folly\Folly.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
  C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\fmt\fmt.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
  C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]
  C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(414,5): error MSB3202: The project file "C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\Common\Common.vcxproj" was not found. [C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln]


"C:\Users\jamie\git\banana_native\apps\banana\windows\banana.sln" (Restore target) (1) ->
"C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj" (_IsProjectRestoreSupported target) (3) ->
  C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'C:\Users\jamie\git\banana_native\apps\banana\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj'.

 ✖ Couldn't restore found packages.config instances. Restoring NuGet packages  - exit error code 1
 ✖ It is possible your installation is missing required software dependencies. Dependencies can be automatically installed by running C:\Users\jamie\git\banana_native\node_modules\react-native-windows\scripts\rnw-dependencies.ps1 from an elevated PowerShell prompt.
For more information, go to http://aka.ms/rnw-deps
Command failed. Re-run the command with --logging for more information.
ELIFECYCLE Command failed with exit code 2302.
```

</details>

What's the most elegant way to solve this?
