### DISCUSSION TITLE
ClangFormat takes over 1 minute to format any single file in a React Native Windows v0.73 Old Arch project

### DISCUSSION THREAD

**Discussion by shirakaba** [microsoft/react-native-windows#14355] [Q&A] [answered]
I do my native code in Visual Studio 2022 rather than Visual Studio Code, and rely on `ClangFormat` to format the C++.

However, the time it takes to run is just agony. No matter the library I'm working on, the size of the file, or the size of the code change made, it takes over a minute to run formatting on an M3 Max MacBook Pro. It affects all React Native Windows apps I've worked on. By comparison, fresh "vanilla" Windows apps format in an instant. It affects ClangFormat whether used through Visual Studio and Visual Studio Code, though the latter does feel a few seconds faster.

I'm not exaggerating – I have to sit through this for hours a day when working on native code:

https://github.com/user-attachments/assets/092a2da8-e815-4af7-8971-9c527bd05c4d

I think my settings are pretty sane:

<img width="757" alt="image" src="https://github.com/user-attachments/assets/d28d52e6-1c07-43ce-ba1e-85d86d50361e" />

And my `.clangformat` file is based on rules I found in either the React Native Windows repo or Facebook's Hermes repo.

<details>
<summary>Show .clangformat</summary>

```yaml
---
AccessModifierOffset: -1
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlinesLeft: true
AlignOperands:   false
AlignTrailingComments: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BraceWrapping:
  AfterClass:      false
  AfterControlStatement: false
  AfterEnum:       false
  AfterFunction:   false
  AfterNamespace:  false
  AfterObjCDeclaration: false
  AfterStruct:     false
  AfterUnion:      false
  BeforeCatch:     false
  BeforeElse:      false
  IndentBraces:    false
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Allman
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakAfterJavaFieldAnnotations: false
BreakStringLiterals: false
ColumnLimit:       120
CommentPragmas:  '^ IWYU pragma:'
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat:   false
ForEachMacros:   [ FOR_EACH_RANGE, FOR_EACH, TEST_CLASS, TEST_CLASS_EX ]
IncludeBlocks: Preserve
IncludeCategories:
  - Regex:           'pch.h'
    Priority:        -1
  - Regex:           '.*\.g\..*'
    Priority:        1
  - Regex:           '^<.*\.h(pp)?>'
    Priority:        2
  - Regex:           '^<.*'
    Priority:        3
  - Regex:           '.*'
    Priority:        4
IndentCaseLabels: true
IndentWidth:     2
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: false
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
ObjCBlockIndentWidth: 2
ObjCSpaceAfterProperty: true
ObjCSpaceBeforeProtocolList: true
PenaltyBreakBeforeFirstCallParameter: 1
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyExcessCharacter: 1000000
PenaltyReturnTypeOnItsOwnLine: 200
PointerAlignment: Right
ReflowComments:  true
SortIncludes:    true
SpaceAfterCStyleCast: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles:  false
SpacesInContainerLiterals: true
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard:        Cpp11
TabWidth:        8
UseTab:          Never
```

</details>

Is there a trick to faster C++ formatting?
