### ISSUE TITLE
NU1101: Unable to find package boost (with GitLab)

### ISSUE THREAD

**Issue by cjhines** [microsoft/react-native-windows#10264]
### Problem Description

I'm trying to build a rn-windows app on a [GitLab Windows Shared Runner](https://about.gitlab.com/blog/2020/01/21/windows-shared-runner-beta/).

I can successfully run the dependency script and it completes without error:
`./node_modules/react-native-windows/scripts/rnw-dependencies.ps1 -Install`

However whenever I run `npx react-native run-windows --arch x64 --release --logging` it fails despite building successfully on my local machine.

```ps
- Build failed with message C:\GitLab-Runner\builds\user\myApp\application\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj : error NU1101: Unable to find package boost. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\GitLab-Runner\builds\user\myApp\application\windows\wintest.sln]. Check your build configuration.
✖ Build failed with message C:\GitLab-Runner\builds\user\myApp\application\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj : error NU1101: Unable to find package boost. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\GitLab-Runner\builds\user\myApp\application\windows\wintest.sln]. Check your build configuration.
Command failed with error MSBuildError: C:\GitLab-Runner\builds\user\myApp\application\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj : error NU1101: Unable to find package boost. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\GitLab-Runner\builds\user\myApp\application\windows\wintest.sln]
```

I tried including boost in my project's `.vcxproj` file, however this changed nothing:
```html
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CppWinRT" Version="2.0.211028.7" />
    <PackageReference Include="boost" Version="1.76.0.0" />
  </ItemGroup>
```

Here is my GitLab pipeline:

```yml
build_windows:
  extends:
    - .shared_windows_runners
  stage: build
  before_script:
    - start powershell
    - cd application
    - ./windows/scripts/dev-mode.ps1
    - refreshenv
  script:
    - choco install nodejs --version 14.20.0 -y --no-progress
    - refreshenv
    - npm ci
    - ./node_modules/react-native-windows/scripts/rnw-dependencies.ps1 -Install
    - refreshenv
    - npx react-native run-windows --arch x64 --release --logging
```

### Steps To Reproduce

1. Initialise RNW application
2. Create pipeline on [GitLab Windows Shared Runner](https://about.gitlab.com/blog/2020/01/21/windows-shared-runner-beta/).
3. `./node_modules/react-native-windows/scripts/rnw-dependencies.ps1 -Install`
4. `npx react-native run-windows --arch x64 --release --logging`

### CLI version

8.0.3

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Memory: 5.47 GB / 7.50 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32630.194 (Visual Studio Community 2019)
  Languages:
    Java: 12.0.2 - C:\Program Files\OpenJDK\jdk-12.0.2\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-windows: 0.69.1 => 0.69.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release
