### ISSUE TITLE
Command `windows` unrecognized

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1175]
I clone `https://github.com/benoitvallon/react-native-nw-react-calculator.git` and run `npm install` multiple time to install all dependencies (https://github.com/npm/npm/issues/10985)

Then run `npm install --save-dev rnpm-plugin-windows`

When I run `react-native windows` I have the following error

```
Command `windows` unrecognized
Usage: react-native <command>

Commands:
  - start: starts the webserver
  - bundle: builds the javascript bundle for offline use
  - unbundle: builds javascript as "unbundle" for offline use
  - new-library: generates a native library bridge
  - link: Adds a third-party library to your project. Example: react-native link awesome-camera
  - android: generates an Android project for your app
  - run-android: builds your app and starts it on a connected Android emulator or device
  - run-ios: builds your app and starts it on iOS simulator
  - upgrade: upgrade your app's template files to the latest version; run this after updating the react-native version in your package.json and running npm install
```
