### ISSUE TITLE
run-windows is Always Run in Release Mode in CI

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5467]
#5283  added this bit of logic to `react-native-init.yml`

```yaml
  - ${{ if not(eq(parameters.configuration, 'Release')) }}:
    - script: |
        echo ##vso[task.setvariable variable=releaseBuildArgs]--release
      displayName: 'Configure extra args for Build project'
```

Both release and debug configs seem to be passing the release flag after this.

E.g. x86 debug runs:
```
npx --no-install react-native run-windows --arch x86 --no-launch --no-deploy --logging --buildLogDirectory d:\a\1\b\x86\Debug\BuildLogs --release
```

x64 release runs:
```
npx --no-install react-native run-windows --arch x64 --no-launch --no-deploy --logging --buildLogDirectory d:\a\1\b\x64\Release\BuildLogs --release
```
